# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('data', jsonfield.fields.JSONField()),
                ('organiser_email_id', models.EmailField(max_length=254)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('O', 'Organiser'), ('P', 'Participant'), ('V', 'Volunteer'), ('M', 'Mentor')], max_length=1)),
                ('hackathon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='users',
            field=models.ManyToManyField(through='Member', to='api.User'),
        ),
    ]
