# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('is_published', models.BooleanField(default=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('organiser', 'Organiser'), ('participant', 'Participant'), ('volunteer', 'Volunteer'), ('mentor', 'Mentor')])),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.TextField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')])),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Max 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('level_of_study', models.TextField(choices=[('high-school', 'High School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('doctoral', 'PhD'), ('other', 'Other')])),
                ('major_of_study', models.CharField(max_length=50)),
                ('school_last_attended', models.CharField(max_length=50, null=True)),
                ('graduation_year', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1950)])),
                ('graduation_month', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tshirt_size', models.TextField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')])),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('street_address', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField()),
                ('social_urls', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('dietary_restrictions', models.TextField(choices=[('halal', 'Halal'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten-free', 'Gluten-free'), ('lactose-intolerant', 'Lactose Intolerant'), ('none', 'None')])),
                ('special_accommodations', models.TextField(null=True)),
                ('technical_interests', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('about_me', models.TextField(null=True)),
                ('sponsors_interested_in', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('prizes_interested_in', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('experience_points', models.IntegerField(default=0)),
                ('badges_links', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('sticker_book_links', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='members',
            field=models.ManyToManyField(through='api.Member', to='api.User'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('hackathon', 'member')]),
        ),
    ]
