# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.FileField(upload_to='other/')),
            ],
        ),
    ]
