# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hacker',
            unique_together=set([('user', 'hackathon', 'role')]),
        ),
    ]
