# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 19:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
