# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170909_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackathon',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='hackathon_id',
            new_name='hackathon',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user_id',
            new_name='user',
        ),
    ]
