# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='logo',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='logo_image_file',
            field=models.ImageField(null=True, upload_to='hackathon_logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_link',
            field=models.TextField(null=True),
        ),
    ]
