# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170910_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='hackathon',
            old_name='users',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='member',
        ),
    ]
