# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171218_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='application_status',
            field=models.TextField(choices=[('accepted', 'Accepted'), ('wait-listed', 'Wait Listed'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='accepted'),
            preserve_default=False,
        ),
    ]
