# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170911_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='User',
        ),
    ]
