# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170911_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
