# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hacker_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hacker',
            name='role',
        ),
    ]
