# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170911_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='organiser_email_id',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='organiser_id',
            field=models.TextField(default=12312312),
            preserve_default=False,
        ),
    ]
