# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170911_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='Member',
        ),
    ]
