# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171230_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=35)),
                ('organization', models.CharField(max_length=75)),
                ('project_link', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hackathon',
            name='max_team_size',
            field=models.PositiveIntegerField(default=3, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='teams_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hackathon'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner_hacker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Hacker'),
        ),
        migrations.AddField(
            model_name='hacker',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Team'),
        ),
    ]
