# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170912_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='organiser_id',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='members',
            field=models.ManyToManyField(through='api.Member', to='api.User'),
        ),
    ]
